### PR TITLE
showcase: add omnic

### PR DESCRIPTION
**Pull request by ccyanxyz**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [x] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [x] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Review by gomyeji — APPROVED** [review]

**Comment by olaszakos** [comment]
Hey @ccyanxyz, thank you for your submission. 

Would you mind
* converting the screenshot png's into webp (lossy) or jpeg? They are a bit heavy with 1MB
* allowing @gomyeji to edit your submission, she'd like to move it further up

**Comment by ccyanxyz** [comment]
> Hey @ccyanxyz, thank you for your submission.
> 
> Would you mind
> 
> * converting the screenshot png's into webp (lossy) or jpeg? They are a bit heavy with 1MB
> * allowing @gomyeji to edit your submission, she'd like to move it further up
> 
> I get good results with ffmpeg.
> 
> Lossless:
> 
> ```
> ffmpeg -i image.png -c:v libwebp -lossless 0 -qscale 90 -compression_level 6 image.webp
> ```
> 
> Lossy:
> 
> ```
> ffmpeg -i image.png -quality 90 image.webp
> ```

Updated, also invited @gomyeji to the repo: https://github.com/rocklabs-io/portal1

**Comment by olaszakos** [comment]
Please follow the [guidelines](https://github.com/dfinity/portal#asset-guidelines) for screenshots, they shouldn't be larger than 1024x576px

**Review by gomyeji — APPROVED** [review]

**Comment by ccyanxyz** [comment]
> Please follow the [guidelines](https://github.com/dfinity/portal#asset-guidelines) for screenshots, they shouldn't be larger than 1024x576px

Screenshots are updated now

**Review by yejidfinity — APPROVED** [review]

**Comment by yejidfinity** [comment]
Hi. Omnic data is added in a different PR and is now live. Could you please close this PR?
However, your logo isn't presenting on our website, please check it and submit another PR with the correct logo.

**Pull request closed without merging**
