### PR TITLE
Allkinds project update for Showcase

### PR DESCRIPTION
**Pull request by allkindsxyz**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by jessiemongeon1** [comment]
Hi @allkindsxyz , 

Could you take a look at the image file you included? It appears to be an invalid image source.

Thank you!

**Comment by allkindsxyz** [comment]
Fixed the image source

**Comment by allkindsxyz** [comment]
Hi Jessie,

Fixed the image.

Best regards,
Dima

**Comment by jessiemongeon1** [comment]
Hi @allkindsxyz , 

Did you intend to close this merge request?

Thanks

**Comment by allkindsxyz** [comment]
No, I am not. Sorry for this.

Best regards
Dima

**Pull request closed without merging**
