### PR TITLE
Sueann/motoko interpreter new

### PR DESCRIPTION
**Pull request by wackyleo459**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by wackyleo459** [comment]
## UPDATE and CHANGES: 
- Motoko Interpreter script with Run Button gets attached to a codeblock with Motoko
- Syntax highlighter for Motoko and Candid uses Highlight.js and Codejar under the hood

    

https://user-images.githubusercontent.com/38238542/174352548-0c78d65d-097b-4fba-ae9e-2ade12c3e764.mov

**Comment by crusso** [comment]
This is great! Looking forward to seeing it live. Note the motoko markdown docs in the repo are quite stale and don't include the all the codeblock attributes that the interpreter plugin is expecting. Updating the motoko docs (ask @hugolgst, I think) should fix that. But even merging this is a huge improvement. Thank you!

**Review by sesi200 — APPROVED** [review]
This is wonderful, thank you very much! Feel free to merge when looks good to you, @wackyleo459  Small question: is it intentional that `static/img/motokoPlayground.png` and `static/img/startBuilding/event_background_image.png` are made larger?

**Comment by wackyleo459** [comment]
@crusso @sesi200 Thanks for the feedback! I've reverted those image sizes, mistake on my part.
I've also updated to the latest interpreter version 0.6.29. Will go ahead and merge this PR!

**Pull request merged**
