### PR TITLE
Add metaforo-icp to showcase

### PR DESCRIPTION
**Pull request by chaochen83**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by sesi200** [comment]
Any chance you can shorten the description a bit? The tile looks very weird compared to the others
image

**Comment by chaochen83** [comment]
Sure @sesi200, stats and description has been shortened, thank you!

**Comment by chaochen83** [comment]
@sesi200 Hello, any update on this pull request? Thanks!

**Review by sesi200 — APPROVED** [review]
Apologies, I must have accidentally dismissed the notification...

**Comment by sesi200** [comment]
Ugh, need to update the branch. Can you maybe give me access to it? There should be a button 'give maintainers write access' on the side

**Comment by chaochen83** [comment]
@sesi200 https://github.com/metaforo/icp-portal/invitations  Invite u as maintain role. Please accept~

**Review by sesi200 — APPROVED** [review]

**Pull request merged**
