### PR TITLE
Feature/add missing examples

### PR DESCRIPTION
**Pull request by letmejustputthishere**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by letmejustputthishere** [comment]
the build fails locally but the respective examples aren't surfaced in the docs so i think we can ignore that?
```
[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/current/references/samples/native-apps/unity_ii_universallink/ii_integration_dapp/:
   -> linking to ./src/universallink_website/assets/.well-known/apple-app-site-association (resolved as: /docs/current/references/samples/native-apps/unity_ii_universallink/ii_integration_dapp/src/universallink_website/assets/.well-known/apple-app-site-association)

- On source page path = /docs/current/references/samples/native-apps/unity_ii_universallink/unity_project/:
   -> linking to ../ii_integration_dapp/src/universallink_website/ (resolved as: /docs/current/references/samples/native-apps/unity_ii_universallink/ii_integration_dapp/src/universallink_website/)

    at throwError (/Users/moritz/projects/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at handleBrokenLinks (/Users/moritz/projects/portal/node_modules/@docusaurus/core/lib/server/brokenLinks.js:153:47)
    at async buildLocale (/Users/moritz/projects/portal/node_modules/@docusaurus/core/lib/commands/build.js:186:5)
    at async tryToBuildLocale (/Users/moritz/projects/portal/node_modules/@docusaurus/core/lib/commands/build.js:41:20)
    at async mapAsyncSequential (/Users/moritz/projects/portal/node_modules/@docusaurus/utils/lib/jsUtils.js:34:24)
    at async Command.build (/Users/moritz/projects/portal/node_modules/@docusaurus/core/lib/commands/build.js:76:21)
[INFO] Docusaurus version: 2.4.3
Node version: v18.17.0
```

**Comment by letmejustputthishere** [comment]
also, the markdown alerts aren't rendered correctly. see #2689

**Comment by jessiemongeon1** [comment]
@letmejustputthishere The build will fail when we try to deploy it though, so these links do need to be fixed from within the Examples repo, then the submodule needs to be updated in this PR to apply the fix.

**Comment by letmejustputthishere** [comment]
@jessiemongeon1 got it, will do that now

**Review by domwoe — APPROVED** [review]

**Pull request merged**
