### PR TITLE
Update showcase.json from Faceless project

### PR DESCRIPTION
**Pull request by HeisenbergLin22**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by domwoe** [comment]
@HeisenbergLin22 Could you please accept the CLA?

**Comment by jennifertrin** [comment]
Hello @HeisenbergLin22, can you please complete the CLA steps listed in this PR?

**Comment by HeisenbergLin22** [comment]
> issue

Hey, I haven't checked my GitHub message for a while, sorry for the late response. I've approved the CLA, and here is the link: https://github.com/dfinity/cla/issues/246#issuecomment-1751608780

**Comment by sa-github-api** [comment]
Dear @HeisenbergLin22,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/247) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

**Comment by HeisenbergLin22** [comment]
> Dear @HeisenbergLin22,
> 
> In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).
> 
> If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/247) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.
> 
> — The DFINITY Foundation

Hey, as you can see from this link: https://github.com/dfinity/cla/issues/247#issuecomment-1751929358 and this link: https://github.com/dfinity/cla/issues/247#issuecomment-1751929812, I copied the sentence exactly to approve the CLA, but somehow the github-actions bot keeps saying ["Your comment does not match the CLA agreement."](https://github.com/dfinity/cla/issues/247#issuecomment-1751929874). Would you please check which part of my comment is invalid? Thanks.

**Comment by jennifertrin** [comment]
> > Dear @HeisenbergLin22,
> > In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).
> > If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/247) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.
> > — The DFINITY Foundation
> 
> Hey, as you can see from this link: [dfinity/cla#247 (comment)](https://github.com/dfinity/cla/issues/247#issuecomment-1751929358) and this link: [dfinity/cla#247 (comment)](https://github.com/dfinity/cla/issues/247#issuecomment-1751929812), I copied the sentence exactly to approve the CLA, but somehow the github-actions bot keeps saying ["Your comment does not match the CLA agreement."](https://github.com/dfinity/cla/issues/247#issuecomment-1751929874). Would you please check which part of my comment is invalid? Thanks.

Hello @HeisenbergLin22, can you please only write a comment without replying?

See this as an example: https://github.com/dfinity/cla/issues/375

**Comment by HeisenbergLin22** [comment]
> > > Dear @HeisenbergLin22,
> > > In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).
> > > If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/247) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.
> > > — The DFINITY Foundation
> > 
> > 
> > Hey, as you can see from this link: [dfinity/cla#247 (comment)](https://github.com/dfinity/cla/issues/247#issuecomment-1751929358) and this link: [dfinity/cla#247 (comment)](https://github.com/dfinity/cla/issues/247#issuecomment-1751929812), I copied the sentence exactly to approve the CLA, but somehow the github-actions bot keeps saying ["Your comment does not match the CLA agreement."](https://github.com/dfinity/cla/issues/247#issuecomment-1751929874). Would you please check which part of my comment is invalid? Thanks.
> 
> Hello @HeisenbergLin22, can you please only write a comment without replying?
> 
> See this as an example: [dfinity/cla#375](https://github.com/dfinity/cla/issues/375)

Hey @jennifertrin , thanks for your suggestion. It [works](https://github.com/dfinity/cla/issues/247#issuecomment-1772142774)

**Comment by jennifertrin** [comment]
Hello @HeisenbergLin22 Can you please add a tag value for Faceless?

**Review by jennifertrin — APPROVED** [review]

**Pull request merged**
