### PR TITLE
Fixed some typos in  deploy_sample_app.md

### PR DESCRIPTION
**Pull request by aubort**
While browsing the documentation I found a few typos that I have fixed. 

There might be one more that I wasn't sure about on row 90 "You have deployed your first ICP dapp locally" Not sure if "ICP" should not be "IC"?

### CODE REVIEW

**Review by sesi200 — APPROVED** [review]
Thanks for the fixes!

**Comment by dprats** [comment]
Thanks for much for these @aubort !

**Comment by dprats** [comment]
@aubort can you please accept the CLA so we can merge this? Thank you!

**Comment by aubort** [comment]
@dprats thanks, I thought I had accepted them yesterday. Done now, hope it worked: https://github.com/dfinity/cla/issues/224#issuecomment-1548119793

**Comment by dprats** [comment]
@aubort hmm should have worked. Let me see

**Comment by dprats** [comment]
@aubort I found the issue. It seems your original message you replied to via email since it has extra _quoted_ text. The CLA bot is not start enough for that (we are working on it).

Can you please reply with just the phrase:

> I, aubort, hereby agree to the DFINITY Foundation's CLA.

Sorry about the back and forth!

**Comment by aubort** [comment]
Ok @dprats. I've resent the email, pasting the sentence as plain text. Did it work now?

**Comment by dprats** [comment]
@aubort appears not... i think you may have to write it via github UI directly... :/

**Comment by dprats** [comment]
@aubort it worked! thanks!

**Comment by aubort** [comment]
@dprats it worked now! Thanks and sorry for the effort it created on your side for 3 typos :|

**Pull request merged**
