### PR TITLE
Request showcase from ITOKA[Undo autoformat]

### PR DESCRIPTION
**Pull request by MCLYang**
Request showcase from ITOKA

  {
    "id": "itoka",
    "name": "ITOKA",
    "oneLiner": "A Leading Infrastructure for Music3.0",
    "website": "https://www.itoka.xyz/",
    "tags": ["NFT", "SocialFi", "Tools / Infrastructure"],
    "description": "The ITOKA project seeks to disrupt the centralized music industry by offering a complete infrastructure solution for the web3 music industry. This includes creation tools, data storage, and music streaming services. The goal of ITOKA is to transform the music industry into a decentralized ecosystem, empowering creators with greater control over their content and a fairer share of revenue.",
    "usesInternetIdentity": true,
    "github": "https://github.com/Itoka-DAO",
    "twitter": "https://twitter.com/itokamusic",
    "stats": "3M+ minutes on-chain streaming",
    "logo": "/img/showcase/itoka_logo.svg",
    "video": "/img/showcase/itoka_video.mp4",
    "videoContentType": "video/mp4",
    "display": "Large",
    "screenshots": ["/img/showcase/itoka_screanshot.svg"]
  }

### CODE REVIEW

**Review by sesi200 — APPROVED** [review]

**Comment by sesi200** [comment]
Thanks for the PR! If you could please accept the CLA (maybe over at https://github.com/dfinity/portal/pull/1157) I'd be happy to merge

**Comment by MCLYang** [comment]
I signed CLA already. The tag didn’t refresh tho

**Comment by sesi200** [comment]
Ugh, let me ping the CLA bot team...

**Comment by marko-k0** [comment]
CLA check.

**Comment by cgundy** [comment]
CLA check.

**Pull request merged**
