### PR TITLE
Fix links.

### PR DESCRIPTION
**Pull request by daniel-wong-dfinity-org**
Not sure how to test my change -> not sure if it is correct. Please, advise.

### CODE REVIEW

**Comment by daniel-wong-dfinity-org** [comment]
Can someone help with this? Not sure how to fix my change. All I know is that I get 404 when I click on these links in the currently deployed version.

**Comment by sesi200** [comment]
When I go to https://internetcomputer.org/docs/current/developer-docs/build/languages/candid/candid-intro, those links are not broken. Can you point me to broken links?

Btw if you go to the latest deployment log (see comment by netlify bot) you can scroll down to the red lines that will tell you what's wrong. In this case, your changes break at least one link.

**Comment by daniel-wong-dfinity-org** [comment]
> When I go to https://internetcomputer.org/docs/current/developer-docs/build/languages/candid/candid-intro, those links are not broken. Can you point me to broken links?

Screen Shot 2022-06-07 at 10 21 06 AM

Screen Shot 2022-06-07 at 10 21 56 AM

> Btw if you go to the latest deployment log (see comment by netlify bot) you can scroll down to the red lines that will tell you what's wrong. In this case, your changes break at least one link.

Yes, I read the log, but I don't understand what is broken about my change. It just says they are wrong, but I do not know how to correct them. Seems to me (and I'm really not sure about this), the link resolver is incorrect, which seems to lead to a) the links being broken in the first place b) incorrectly identifying my link targets as not existing.

**Comment by sesi200** [comment]
Ah, I see: I had a cached version somehow. I'll try to use private windows for that from now on...

Looking at the structure, the files are located in the _same_ folder, not in the parent directory. Can you try adding the `.md` extension to the files maybe?

**Comment by sesi200** [comment]
@daniel-wong-dfinity-org I tried it with the extension. Can you confirm that it works in the preview?

**Comment by daniel-wong-dfinity-org** [comment]
The links work when I go here: https://deploy-preview-221--icportal.netlify.app/docs/current/developer-docs/build/languages/candid/candid-intro/

**Review by sesi200 — APPROVED** [review]

**Pull request merged**
