### PR TITLE
Add Odoc

### PR DESCRIPTION
**Pull request by aliscie**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [x] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by sa-github-api** [comment]
Dear @aliscie,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/464) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

**Comment by aliscie** [comment]
Done

**Comment by aliscie** [comment]
> Dear @aliscie,
> 
> In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).
> 
> If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/464) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.
> 
> — The DFINITY Foundation

The run workflow button seams to be disabled

**Comment by dprats** [comment]
> The run workflow button seams to be disabled

thanks for letting us know. let me ping folks.

**Comment by jennifertrin** [comment]
@aliscie Thank you for the submission. We also received your request to add your project to the Ecosystem page as part of your Milestone Review. We can also add Odoc on your behalf.

**Comment by olaszakos** [comment]
@aliscie there were syntax errors in the JSON with the extra commas. Now the JSON is valid, but you need to add the logo file to this repository, for example https://github.com/dfinity/portal/pull/2744/files

**Comment by aliscie** [comment]
> @aliscie there were syntax errors in the JSON with the extra commas. Now the JSON is valid, but you need to add the logo file to this repository, for example https://github.com/dfinity/portal/pull/2744/files
Screenshot 2024-04-22 at 4 25 23 PM
I can't upload a file

**Comment by aliscie** [comment]
@olaszakos  @jennifertrin So, how can we proceed with this?

**Comment by jennifertrin** [comment]
@aliscie We have added Odoc to the ecosystem page using the same info here/submitted to us via the Airtable form.

**Pull request closed without merging**
