### PR TITLE
Update logo requirements

### PR DESCRIPTION
**Pull request by sea-snake**
Update logo requirements, include recommendations for optimizing file size.

- [x] Follows the [developer docs style guide](style-guide.md).
- [x] Follows the [best practices and guidelines](README.md#best-practices).
- [x] New documentation pages include [document tags](README.md#document-tags).
- [x] New documentation pages include [SEO keywords](README#seo-keywords).
- [x] New documents are in the `.mdx` file format to support the previous two components. 
- [x] New documents are registered in [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js), otherwise, it will not appear in the
  side navigation bar.
- [x] Make sure that the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file is
  filled with new documents that you added. This way we can ensure that future Pull Requests are reviewed by the right people.

### CODE REVIEW

**Comment by meodai** [comment]
Could you elaborate on why you want to remove WebP? It’s actually the smallest format of the three. If anything, I’d consider removing PNG instead and adding a max file size (KB) requirement to ensure consistency.

That said, keep in mind that not all tools export WebP natively, which might pose challenges for some contributors. Also, SVGs can be tricky since their size depends heavily on the complexity of the logo.

**Comment by sea-snake** [comment]
> Could you elaborate on why you want to remove WebP? It’s actually the smallest format of the three.
My bad, didn't intend to remove webp, adding it back.

Since it's regarding logos, in most cases SVG would be a smaller file size and also scale when used in various sizes.

**Comment by meodai** [comment]
@sea-snake I would typically agree but we had a few cases where the SVGs were huge. 

My proposal would be:

screenshots: jpeg / webP (specify the PX size and a max KB size maybe max 300?)
logo: webP or svg (50kb max?)

**Review by jennifertrin — APPROVED** [review]

**Comment by sea-snake** [comment]
> @sea-snake I would typically agree but we had a few cases where the SVGs were huge.
> logo: webP or svg (50kb max?)
50kb is already too much right now with the II canister WASM size limitations, we're aiming for 4kb or less with max 10kb.

I added recommended online tooling for file size optimizations in this PR that saves roughly 70% in most cases, compared to explicit file size limits this seems like a more proactive approach to enable users to keep file sizes optimal.

**Comment by meodai** [comment]
@sea-snake I don't feel strongly about it. LGTM

**Pull request merged**
