### PR TITLE
/samples page changes

### PR DESCRIPTION
**Pull request by olaszakos**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by domwoe** [comment]
Could you add a paragraph to the Readme on how to add a new sample project?

**Comment by olaszakos** [comment]
> Could you add a paragraph to the Readme on how to add a new sample project?

@domwoe see https://github.com/dfinity/portal/tree/akos/clean-up-community-samples#adding-community-sample-projects

**Comment by domwoe** [comment]
Hey @olaszakos,

sorry to nitpick, but could you change the title in line with the other titles, i.e Community-created sample projects?
Also, I'm not part of editorial and can't review/approve this PR.

**Comment by olaszakos** [comment]
> Community-created sample projects

@domwoe  Like this? 
image

**Comment by domwoe** [comment]
No, just in the readme ;) There are 2 other sections that explain adding community-created resources before.

**Comment by olaszakos** [comment]
Should be done @domwoe

**Review by artkorotkikh-dfinty — APPROVED** [review]

**Pull request merged**
