### PR TITLE
Mikhail/docs revamp

### PR DESCRIPTION
**Pull request by mikhail-turilin-dfinity**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by dfx-json** [comment]
@olaszakos @sesi200 this is ready for review.

@olaszakos the only thing I can't figure out is how to make the "Guides" navbar item highlight (in pink) when we are on the `/developer-docs` route. any ideas?

**Comment by sesi200** [comment]
There's still a few broken links, mostly from updated submodules. You can run `git submodule update` to update them to the latest status.

**Comment by dfx-json** [comment]
> There's still a few broken links, mostly from updated submodules. You can run `git submodule update` to update them to the latest status.

@sesi200 just updated submodules

**Comment by olaszakos** [comment]
@sesi200 do you know what needs to be done to get past the cla check?

**Pull request closed without merging**
