### PR TITLE
solve mismatched types error

### PR DESCRIPTION
**Pull request by KevynTang**
original search function leads to an `mismatched types` compile error, maybe modify it like this is the correct way to solve the issue?

### CODE REVIEW

**Comment by aisconnolly** [comment]
@MurielPinho  or @olaszakos does it help the search?

**Comment by MurielPinho** [comment]
> @MurielPinho or @olaszakos does it help the search?

This is related to the cdk-rs search function, would need @sesi200 opinion

**Comment by sesi200** [comment]
`cdk-rs` is not my forte, I'll delegate this one to @lwshang

**Comment by adamspofford-dfinity** [comment]
Thank you for noticing the error! But your version has the very thing that ManualReply exists to remove the need for - cloning borrowed values. The only actual needed change is moving the final return value inside the `with` closure.

**Comment by KevynTang** [comment]
> Thank you for noticing the error! But your version has the very thing that ManualReply exists to remove the need for - cloning borrowed values. The only actual needed change is moving the final return value inside the `with` closure.

Thank you! Learned a lot of things via this PR 🥳

**Pull request closed without merging**
