### PR TITLE
Added link to IC4J Java Candid

### PR DESCRIPTION
**Pull request by rdobrik**
IC4J Candid implementation provides serialization and deserialization from/to Java types (primitives, pojos, jackson,gson, dom, jaxb) to/from Candid.

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Review by sesi200 — APPROVED** [review]
Cool project! Glad to have it linked

**Comment by rdobrik** [comment]
Awesome, thanks! Let me check where else I can add link to my project. I think it's already in Agents chapter.

**Comment by domwoe** [comment]
The tooling site would be a fit as well: https://internetcomputer.org/tooling
https://github.com/dfinity/portal#community-created-developer-tools

**Comment by rdobrik** [comment]
Yes, Dominic, let me add it there, Agent and additional packages like Java Internet Identity, Java IC Management and also that Apache Camel component I am working on. That one actually I want to add to official Apache Camel repository when is finished.

**Pull request merged**
