### PR TITLE
Adding Nuvlio Assets for the Show case page

### PR DESCRIPTION
**Pull request by ChiefEngOfficer**
Related to the https://github.com/dfinity/portal/pull/2172#issuecomment-1816862806

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by sa-github-api** [comment]
Dear @ChiefEngOfficer,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/408) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

**Review by jennifertrin — CHANGES_REQUESTED** [review]
1. Can you please add a JSON about Nuvlio?
2. Can you please also go through the CLA steps?

**Comment by jennifertrin** [comment]
> 1. Can you please add a JSON about Nuvlio?
> 2. Can you please also go through the CLA steps?

@ChiefEngOfficer Can you please review the following?

**Comment by jennifertrin** [comment]
> > 1. Can you please add a JSON about Nuvlio?
> > 2. Can you please also go through the CLA steps?
> 
> @ChiefEngOfficer Can you please review the following?

Can you please review the following by Friday, December 22nd? We will close this PR if it not resolved by then.

**Comment by jennifertrin** [comment]
> > > 1. Can you please add a JSON about Nuvlio?
> > > 2. Can you please also go through the CLA steps?
> > 
> > 
> > @ChiefEngOfficer Can you please review the following?
> 
> Can you please review the following by Friday, December 22nd? We will close this PR if it not resolved by then.

@ChiefEngOfficer  We are closing this PR due to a lack of response. If you want to add the QSTN marketplace to the Ecosystem page, please open another PR.

**Pull request closed without merging**
