### PR TITLE
added cdk optimizer dependency

### PR DESCRIPTION
**Pull request by letmejustputthishere**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [x] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [x] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by sesi200** [comment]
AFAIK with the latest versions of dfx the optimizer is not necessary anymore. Does it still work if we leave this out?

**Comment by letmejustputthishere** [comment]
let me find out. if this is the case then instead of adding it to all of the tutorials, we have to remove the step from the quickstart for the rust cdk

**Comment by ggreif** [comment]
> AFAIK with the latest versions of dfx the optimizer is not necessary anymore. Does it still work if we leave this out?

@chenyan-dfinity ^^

**Comment by letmejustputthishere** [comment]
i can confirm that the `shrink WASM module size` step is present even after running `cargo uninstall ic-cdk-optimizer`.

also i digged [this](https://forum.dfinity.org/t/wasm-module-contains-a-function-that-is-too-complex/15407/18?u=cryptoschindler) up in the forum.

if it is true, we should edit/remove the entire `optimize rust` section. will make a pr for that

**Pull request closed without merging**
