### PR TITLE
Update showcase.json

### PR DESCRIPTION
**Pull request by HeisenbergLin22**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by olaszakos** [comment]
Hi @HeisenbergLin22 , thanks for your submission. It appears that the project is already uploaded with similar data at https://github.com/dfinity/portal/blob/master/showcase.json#L2844

If you need to update the fields, please open a new PR.

**Comment by ChiefEngOfficer** [comment]
{
    "id": "nuvlio",
    "name": "Nuvlio",
    "oneLiner": "Nuvlio Commodities Risk Intelligence Oracles - The next age in analysis and monitoring of commodities financial services.",
    "website": "https://nuvlio.com/",
    "tags": [
      "DeFi", "Tools / Infrastructure"
    ],
    "description": "Nuvlio provides global, historic and real-time agriculture commodities with data, analytics and scoring since January 2000 up to today for any place on Earth. Any DEFI, fintech or financial players that operates credit, insurance, reinsurance, trade finance or environmental services can leverage Nuvlio Commodities Risk Intelligence Oracles to automatize from acquisition up to the end of the financial contracts, with verifiable information and access through the Internet Computer.",
    "usesInternetIdentity": true,
    "twitter":"https://twitter.com/nuvlio",
    "stats": "5+ million hectares under analysis",
    "display": "Large",
    "logo": "/img/showcase/nuvlio_logo.png",
    "screenshots": [
      "/img/showcase/nuvlio_screenshot.png"
    ]
  }

**Comment by jennifertrin** [comment]
> { "id": "nuvlio", "name": "Nuvlio", "oneLiner": "Nuvlio Commodities Risk Intelligence Oracles - The next age in analysis and monitoring of commodities financial services.", "website": "https://nuvlio.com/", "tags": [ "DeFi", "Tools / Infrastructure" ], "description": "Nuvlio provides global, historic and real-time agriculture commodities with data, analytics and scoring since January 2000 up to today for any place on Earth. Any DEFI, fintech or financial players that operates credit, insurance, reinsurance, trade finance or environmental services can leverage Nuvlio Commodities Risk Intelligence Oracles to automatize from acquisition up to the end of the financial contracts, with verifiable information and access through the Internet Computer.", "usesInternetIdentity": true, "youtube":"https://youtu.be/4rxXdldHPSc", "twitter":"https://twitter.com/nuvlio_com", "stats": "5+ million hectares under analysis", "display": "Large", "logo": "/img/showcase/nuvlio_logo.png", "screenshots": [ "/img/showcase/nuvlio_screenshot.png" ] }

@ChiefEngOfficer Can you please update the code directly?

**Comment by jennifertrin** [comment]
@HeisenbergLin22 As advised, the Faceless Project has already been added to the showcase. If you are looking to update the project info, please open a new PR.

**Pull request closed without merging**
