### PR TITLE
Update showcase.json

### PR DESCRIPTION
**Pull request by tanteikg**
to include AStablish into showcase.json

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by jessiemongeon1** [comment]
Dear @tanteikg ,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's CLA[1](https://github.com/dfinity/portal/pull/1686#user-content-fn-1-32ee3daf3ab88b7904e0947d8da02c40).

If you decide to agree with it, please visit this https://github.com/dfinity/cla/issues/297 and read the instructions there.

— The DFINITY Foundation

**Review by jessiemongeon1 — APPROVED** [review]

**Comment by jessiemongeon1** [comment]
Hi @tanteikg , please review and agree to the DFINITY CLA to have this PR merged. Thank you!

**Comment by jennifertrin** [comment]
> Dear @tanteikg,
> 
> In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's CLA[1](#user-content-fn-1-68e8f596210c6ff5dc788b4884b1560a).
> 
> If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/302) and read the instructions there.
> 
> — The DFINITY Foundation
> 
> ## Footnotes
> 1. Contributor License Agreement [↩](#user-content-fnref-1-68e8f596210c6ff5dc788b4884b1560a)

Can you please go through this CLA process by Friday, October 20th?

**Comment by jennifertrin** [comment]
Hello @tanteikg Due to the lack of response, we will be closing this PR. If you would still like to add AStablish to the Ecosystem page, please open a new PR.

**Pull request closed without merging**
