### PR TITLE
Datanome Project addition to Showcase

### PR DESCRIPTION
**Pull request by oelamri**
**Done:**
- Added Datanome to `showcase.js`
- Added Datanome logo to `/static/img/showcase`

### CODE REVIEW

**Review by yejidfinity — APPROVED** [review]

**Review by yejidfinity — APPROVED** [review]

**Review by yejidfinity — APPROVED** [review]

**Review by sesi200 — APPROVED** [review]

**Comment by sesi200** [comment]
Please merge master or give maintainers write access to your branch so I can merge. There should be a checkbox on the right

**Comment by domwoe** [comment]
@oelamri Could you please resolve the conflicts?

**Comment by jennifertrin** [comment]
@oelamri Can you please resolve the conflicts by **Thursday, October 26th**?

**Comment by jennifertrin** [comment]
Hello @oelamri, due to the lack of response, we will be closing this PR. If you would still like to add Datanome to the Ecosystem page, please open a new PR.

**Pull request closed without merging**
