### PR TITLE
Add Loka to DFINITY Portal Showcase

### PR DESCRIPTION
**Pull request by vxyagr**
Hi DFINITY team, please kindly check our Loka showcase submission

### CODE REVIEW

**Comment by sa-github-api** [comment]
Dear @vxyagr,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/414) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

**Comment by jennifertrin** [comment]
> Dear @vxyagr,
> 
> In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).
> 
> If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/414) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.
> 
> — The DFINITY Foundation

@vxyagr Can you please go through these CLA steps?

**Comment by vxyagr** [comment]
hi @jennifertrin i have finished the CLA steps, please kindly continue this workflow
thank you

**Comment by vxyagr** [comment]
hi @jennifertrin i have signed the[ CLA ](https://github.com/dfinity/cla/issues/414)
Please kindly rerun the check, thank you

**Comment by vxyagr** [comment]
seems my showcase is having an error in image filename.
i will close this and submit a new one

**Pull request closed without merging**
