### PR TITLE
/roadmap page wip

### PR DESCRIPTION
**Pull request by olaszakos**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by dprats** [comment]
@harpa12 @artkorotkikh-dfinty 

I pushed up some copy changes. Let me explain my rationale (which you are more than welcome to undo):

1. Not all of the projects listed have had NNS proposals
2. Emphasized IC Blockchain

For all other changes, I will instead just post comments in this PR.

**Comment by dprats** [comment]
@harpa12 @artkorotkikh-dfinty 

Not a blocker to push to production, but I think we should make space in the page to highlight the Monthly summaries like this one: https://forum.dfinity.org/t/update-on-the-ic-roadmap-july-2022-summary/14615

Rationale:

1. These summaries show a history of progress
2. These summaries explain the "stack-based" mentality and shift from linear thinking. In particular, Sam's image of the stacks I think is very helpful for understanding.

I think these summaries should be very evident (not buried at the bottom), but something users can see immediately. Even if its a banner announcement that says "read latest monthly update on roadmap" etc...

**Comment by dprats** [comment]
@samuelburri 

Re: "Custom domain names"

The description listed here is surprising. 

_"Custom Domain Names
This features enables dapps on the Internet Compute to be indexed by search engines and previewed on social media (e.g., Twitter cards). Boundary nodes redirect requests from crawlers and bots (e.g., Googlebot) to raw in order to avoid loading the service worker."_

I thought the 90% goal of custom domains was about user friendly URLs, not search indexing. I could be wrong, so can you please verify?

**Comment by dprats** [comment]
@samuelburri 

re: "Canister Blacklisting on Boundary Nodes"

I think this may be a better forum link. Wdyt?

forum link: https://forum.dfinity.org/t/path-forward-on-leveraging-boundary-nodes-for-content-filtering/10911

cc @harpa12

**Comment by dprats** [comment]
**Re: "Node Onboarding Improvements"**

@samuelburri we need some copy here (though this should not block pushing to production).

**Comment by dprats** [comment]
Any place where we can link to the long-term R&D projects: https://forum.dfinity.org/t/motion-proposals-on-long-term-r-d-plans/9261

**Comment by harpa12** [comment]
> 
> 
> 
> > @samuelburri @harpa12
> > 
> > Re: "Custom domain names"
> > 
> > The description listed here is surprising. I believe it is a duplicate.
> > 
> > _"Custom Domain Names This features enables dapps on the Internet Compute to be indexed by search engines and previewed on social media (e.g., Twitter cards). Boundary nodes redirect requests from crawlers and bots (e.g., Googlebot) to raw in order to avoid loading the service worker."_
> > 
> > As you can see, the exact same copy is used here:
> > 
> > _"SEO and Streaming Support This features enables dapps on the Internet Computer to be indexed by search engines and previewed on social media (e.g., Twitter cards). Boundary nodes redirect requests from crawlers and bots (e.g., Googlebot) to raw in order to avoid loading the service worker."_

@dprats @samuelburri : This was mistake on my part. I have already corrected it.

**Review by dprats — APPROVED** [review]

**Pull request merged**
