### PR TITLE
appended icpipeline to the toolingItems.js file of IC Community tools

### PR DESCRIPTION
**Pull request by mbeekman**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Review by sesi200 — APPROVED** [review]
Thanks for the PR! Nice to have you on the list.

Your description is extremely generic. I'm ok merging this, but are you sure you don't want to write something more descriptive?

**Comment by mbeekman** [comment]
Thanks for looking out, we updated the description to add more details ... please let me know if you need anything else ... appreciate it very much.
-M

**Review by sesi200 — APPROVED** [review]

**Comment by sesi200** [comment]
LGTM, now it's just a matter of getting the PR to merge. This repo's settings require your branch to be fully merged with master. If you could repeatedly merge master into your branch that would be great, until I catch it being allowed to merge at some point in time. I'll check in a few times a day.

**Comment by mbeekman** [comment]
I think I did it? ... lmk if I need to do something else? ... and thanks :)

**Comment by mbeekman** [comment]
looks like we are live ... thanks again ...

**Pull request merged**
