### PR TITLE
QSTN marketplace entry added

### PR DESCRIPTION
**Pull request by sekmet**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by sa-github-api** [comment]
Dear @sekmet,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/412) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

**Comment by jennifertrin** [comment]
> Dear @sekmet,
> 
> In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).
> 
> If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/412) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.
> 
> — The DFINITY Foundation

@sekmet Please go through these CLA steps before this can be reviewed.

**Comment by jennifertrin** [comment]
> Thank you for your contribution to the IC Developer Portal. Before submitting your Pull Request, please make sure that:
> 
> * [ ]  You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
> * [ ]  You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

@sekmet Can you please allow anyone to edit https://github.com/QSTN-US/icp-portal/? We need to resolve the merge conflicts.

**Comment by jennifertrin** [comment]
> > Thank you for your contribution to the IC Developer Portal. Before submitting your Pull Request, please make sure that:
> > 
> > * [ ]   You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
> > * [ ]   You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.
> 
> @sekmet Can you please allow anyone to edit https://github.com/QSTN-US/icp-portal/? We need to resolve the merge conflicts.

@sekmet Can you please allow anyone to edit https://github.com/QSTN-US/icp-portal/ or handle the merge conflicts by Friday, December 22nd? We will close this PR if the merge conflicts are not resolved by then.

**Comment by jennifertrin** [comment]
@sekmet We are closing this PR due to a lack of response. If you want to add the QSTN marketplace to the Ecosystem page, please open another PR.

**Pull request closed without merging**
