### PR TITLE
Azle and kybra languages menu

### PR DESCRIPTION
**Pull request by lastmjs**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [x] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [x] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by sesi200** [comment]
Thanks for all the PRs, Jordan! Do you have a good reason for updating the submodules or is that an accident? (applies to all your PRs)

**Comment by lastmjs** [comment]
I think I just followed the steps from the README:

```bash
cd portal/
git submodule update --init
npm install
npm start
```

Then I made my changes just to the relevant areas and committed. Do you know why these changes occurred and how I should remove them?

**Comment by sesi200** [comment]
I don't know why they appeared. I think if you do

```
git checkout master
git submodule update
git checkout <your branch>
git add * # especially submodules
```
they should be back to the same as `master`

**Comment by lastmjs** [comment]
I've tried doing the commands you suggested multiple times on different branches, but nothing seems to change.

**Comment by jessiemongeon1** [comment]
These pages are now linked in the corresponding Azle and Kybra pages under 'Languages'. This PR appears to be outdated/not needed. Closing this PR to clean up the repo. Please feel free to reopen if you think this should be revisited.

**Pull request closed without merging**
