### PR TITLE
add Dmail network to showcase

### PR DESCRIPTION
**Pull request by bin-dogami**

### CODE REVIEW

**Comment by sa-github-api** [comment]
Dear @bin-dogami,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/458) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

**Comment by bin-dogami** [comment]
> Dear @bin-dogami,
> 
> In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).
> 
> If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/458) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.
> 
> — The DFINITY Foundation

hi, how to  re-trigger the workflow on this PR? I cannot find the way to re-trigger

**Comment by jennifertrin** [comment]
@bin-dogami DMail is already listed on the ecosystem page. Can you please check the listing under id: dmail and update that instead?

**Comment by bin-dogami** [comment]
> @bin-dogami DMail is already listed on the ecosystem page. Can you please check the listing under id: dmail and update that instead?

Ok, I delete the old code and 2 pictures

**Pull request closed without merging**
