### PR TITLE
Add Isotopic Game Store to Showcase

### PR DESCRIPTION
**Pull request by fourthedesign**
Change to add Isotopic Game Store (development grant project) to showcase.

### CODE REVIEW

**Comment by sa-github-api** [comment]
Dear @fourthedesign,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/406) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

**Comment by jennifertrin** [comment]
> Dear @fourthedesign,
> 
> In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).
> 
> If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/406) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.
> 
> — The DFINITY Foundation

@fourthedesign Can you please go through these steps?

**Comment by jennifertrin** [comment]
@fourthedesign Can you please resolve the merge conflicts or allow us to edit the branch for us to resolve the merge conflicts ourselves?

**Comment by jennifertrin** [comment]
@fourthedesign Can you please resolve merge conflicts?

**Comment by jennifertrin** [comment]
@fourthedesign Can you please allow anyone to edit https://github.com/IsotopicIO/dfinity-portal? We will need to resolve the merge conflicts.

**Comment by fourthedesign** [comment]
Apologies for the delay @jennifertrin , we pushed a commit resolving the conflict.

**Review by jennifertrin — APPROVED** [review]

**Comment by jennifertrin** [comment]
> Apologies for the long delay @jennifertrin , we pushed a commit resolving the conflict.

Thank you for the update!

**Pull request merged**
