### PR TITLE
Vibeverse showcase

### PR DESCRIPTION
**Pull request by roger-rangel**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [x] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Review by csepreghy — COMMENTED** [review]
Links are broken, please update them

**Comment by roger-rangel** [comment]
> Links are broken, please update them

Links should be fixed now 👍

**Comment by sesi200** [comment]
Logo looks broken. Usually a re-upload fixes it

**Comment by roger-rangel** [comment]
> Logo looks broken. Usually a re-upload fixes it

thanks for pointing this out 🙏 Just fixed the path for our logo 👍

**Review by sesi200 — APPROVED** [review]

**Comment by sesi200** [comment]
Oh man, the CLA bot broke really hard this time... would you mind going through the flow again (🤦 ) over here? https://github.com/dfinity/cla/issues/273

**Comment by roger-rangel** [comment]
> Oh man, the CLA bot broke really hard this time... would you mind going through the flow again (🤦 ) over here? [dfinity/cla#273](https://github.com/dfinity/cla/issues/273)

Just signed the CLA again 👍

**Comment by roger-rangel** [comment]
@sesi200 Hi there! Can we open a new pull request again so we can add our new logo and update the description?

**Comment by roger-rangel** [comment]
@sesi200 we would also like to redirect them to vibeverse.xyz, instead of our frontend canister 👍

**Pull request merged**
